# Generated by Django 2.2.3 on 2019-07-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_job', models.CharField(max_length=24)),
                ('tipo', models.IntegerField(choices=[(1, 'CNH'), (2, 'RG'), (3, 'COMPROVANTE RENDA'), (4, 'COMPROVANTE RESIDENCIA'), (5, 'CRLV')])),
            ],
        ),
    ]
